In [16]:
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import tkinter as tk
from tkinter import filedialog, Label

#فرا خوانی کتاب خانه ها

In [38]:

def load_images_from_folder(folder, label, size=(64, 64)):
    images = []
    labels = []
    for filename in os.listdir(folder):
        filepath = os.path.join(folder, filename)
        if os.path.isfile(filepath):
            img = cv2.imread(filepath)
            if img is not None:
                img = cv2.resize(img, size)
                images.append(img.flatten())
                labels.append(label)
    return images, labels

# اماده کردن داده های عکس با استفاده از کتاب خانه cv2

In [39]:

folder_405 = r"D:\hosh\amozesh\405"
folder_206 = r"D:\hosh\amozesh\206"

#انتخاب مسیر پوشه های انتخاب تصویر 

In [40]:

data_405, labels_405 = load_images_from_folder(folder_405, label=0)  
data_206, labels_206 = load_images_from_folder(folder_206, label=1)  
#در اینجا به تصاویر لیبل میدهیم

In [49]:

X = np.array(data_405 + data_206)
y = np.array(labels_405 + labels_206)
print(X,y)
# ادغام داده های به x و y

[[ 52  77  87 ... 180 190 204]
 [ 52  77  87 ... 180 190 204]
 [255 255 255 ... 255 255 255]
 ...
 [140 140 140 ...  88  88  88]
 [174 164 140 ... 255 255 255]
 [252 254 254 ... 252 254 254]] [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1]


In [50]:

X = X / 255.0
print(X)
#باینری کردن تصاویر

[[0.20392157 0.30196078 0.34117647 ... 0.70588235 0.74509804 0.8       ]
 [0.20392157 0.30196078 0.34117647 ... 0.70588235 0.74509804 0.8       ]
 [1.         1.         1.         ... 1.         1.         1.        ]
 ...
 [0.54901961 0.54901961 0.54901961 ... 0.34509804 0.34509804 0.34509804]
 [0.68235294 0.64313725 0.54901961 ... 1.         1.         1.        ]
 [0.98823529 0.99607843 0.99607843 ... 0.98823529 0.99607843 0.99607843]]


In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
 #تقسیم داده ها به اموزش و تست کردن تصاویر
 #در این جا میزان دقت بالا پایین میشود

In [45]:

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
# فراخوانی الگوریتم

KNeighborsClassifier(n_neighbors=3)

In [46]:

y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model accuracy: {accuracy * 100:.2f}%")

# میزان دقت

Model accuracy: 50.00%


In [48]:

root = tk.Tk()
root.title("Car Model Classifier")

frame = tk.Frame(root, width=300, height=150, bg="white")
frame.pack(pady=20)

button = tk.Button(root, text="Select Image", command=open_image)
button.pack(pady=10)

result_label = Label(root, text="Prediction will appear here", bg="white", fg="black")
result_label.pack()

root.mainloop()

#ایجاد و دریافت تصویر از کاربر 

Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Users\novin.co\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "C:\Users\novin.co\AppData\Local\Temp\ipykernel_12836\3819306762.py", line 25, in open_image
    image_label.config(image=img_tk)
  File "c:\Users\novin.co\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "c:\Users\novin.co\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!label2"
